CMD$ reraise.py 2
Python version: 3.7.4
In task1().
Start task2().
BAD! Digesting OSError.
Traceback (most recent call last):
  File "D:\gitw\trivials\python\reraise\reraise.py", line 38, in <module>
    job2()
  File "D:\gitw\trivials\python\reraise\reraise.py", line 27, in job2
    task2()
  File "D:\gitw\trivials\python\reraise\reraise.py", line 11, in task2
    fh = open("somefile.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'somefile.txt'
